// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-population-types-api/config"
	"github.com/ONSdigital/dp-population-types-api/service"
	"net/http"
	"sync"
)

// Ensure, that InitialiserMock does implement service.Initialiser.
// If this is not the case, regenerate this file with moq.
var _ service.Initialiser = &InitialiserMock{}

// InitialiserMock is a mock implementation of service.Initialiser.
//
// 	func TestSomethingThatUsesInitialiser(t *testing.T) {
//
// 		// make and configure a mocked service.Initialiser
// 		mockedInitialiser := &InitialiserMock{
// 			GetCantabularClientFunc: func(cfg config.CantabularConfig) service.CantabularClient {
// 				panic("mock out the GetCantabularClient method")
// 			},
// 			GetHTTPServerFunc: func(bindAddr string, router http.Handler) service.HTTPServer {
// 				panic("mock out the GetHTTPServer method")
// 			},
// 			GetHealthCheckFunc: func(cfg *config.Config, time string, commit string, version string) (service.HealthChecker, error) {
// 				panic("mock out the GetHealthCheck method")
// 			},
// 			GetResponderFunc: func() service.Responder {
// 				panic("mock out the GetResponder method")
// 			},
// 		}
//
// 		// use mockedInitialiser in code that requires service.Initialiser
// 		// and then make assertions.
//
// 	}
type InitialiserMock struct {
	// GetCantabularClientFunc mocks the GetCantabularClient method.
	GetCantabularClientFunc func(cfg config.CantabularConfig) service.CantabularClient

	// GetHTTPServerFunc mocks the GetHTTPServer method.
	GetHTTPServerFunc func(bindAddr string, router http.Handler) service.HTTPServer

	// GetHealthCheckFunc mocks the GetHealthCheck method.
	GetHealthCheckFunc func(cfg *config.Config, time string, commit string, version string) (service.HealthChecker, error)

	// GetResponderFunc mocks the GetResponder method.
	GetResponderFunc func() service.Responder

	// calls tracks calls to the methods.
	calls struct {
		// GetCantabularClient holds details about calls to the GetCantabularClient method.
		GetCantabularClient []struct {
			// Cfg is the cfg argument value.
			Cfg config.CantabularConfig
		}
		// GetHTTPServer holds details about calls to the GetHTTPServer method.
		GetHTTPServer []struct {
			// BindAddr is the bindAddr argument value.
			BindAddr string
			// Router is the router argument value.
			Router http.Handler
		}
		// GetHealthCheck holds details about calls to the GetHealthCheck method.
		GetHealthCheck []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Config
			// Time is the time argument value.
			Time string
			// Commit is the commit argument value.
			Commit string
			// Version is the version argument value.
			Version string
		}
		// GetResponder holds details about calls to the GetResponder method.
		GetResponder []struct {
		}
	}
	lockGetCantabularClient sync.RWMutex
	lockGetHTTPServer       sync.RWMutex
	lockGetHealthCheck      sync.RWMutex
	lockGetResponder        sync.RWMutex
}

// GetCantabularClient calls GetCantabularClientFunc.
func (mock *InitialiserMock) GetCantabularClient(cfg config.CantabularConfig) service.CantabularClient {
	if mock.GetCantabularClientFunc == nil {
		panic("InitialiserMock.GetCantabularClientFunc: method is nil but Initialiser.GetCantabularClient was just called")
	}
	callInfo := struct {
		Cfg config.CantabularConfig
	}{
		Cfg: cfg,
	}
	mock.lockGetCantabularClient.Lock()
	mock.calls.GetCantabularClient = append(mock.calls.GetCantabularClient, callInfo)
	mock.lockGetCantabularClient.Unlock()
	return mock.GetCantabularClientFunc(cfg)
}

// GetCantabularClientCalls gets all the calls that were made to GetCantabularClient.
// Check the length with:
//     len(mockedInitialiser.GetCantabularClientCalls())
func (mock *InitialiserMock) GetCantabularClientCalls() []struct {
	Cfg config.CantabularConfig
} {
	var calls []struct {
		Cfg config.CantabularConfig
	}
	mock.lockGetCantabularClient.RLock()
	calls = mock.calls.GetCantabularClient
	mock.lockGetCantabularClient.RUnlock()
	return calls
}

// GetHTTPServer calls GetHTTPServerFunc.
func (mock *InitialiserMock) GetHTTPServer(bindAddr string, router http.Handler) service.HTTPServer {
	if mock.GetHTTPServerFunc == nil {
		panic("InitialiserMock.GetHTTPServerFunc: method is nil but Initialiser.GetHTTPServer was just called")
	}
	callInfo := struct {
		BindAddr string
		Router   http.Handler
	}{
		BindAddr: bindAddr,
		Router:   router,
	}
	mock.lockGetHTTPServer.Lock()
	mock.calls.GetHTTPServer = append(mock.calls.GetHTTPServer, callInfo)
	mock.lockGetHTTPServer.Unlock()
	return mock.GetHTTPServerFunc(bindAddr, router)
}

// GetHTTPServerCalls gets all the calls that were made to GetHTTPServer.
// Check the length with:
//     len(mockedInitialiser.GetHTTPServerCalls())
func (mock *InitialiserMock) GetHTTPServerCalls() []struct {
	BindAddr string
	Router   http.Handler
} {
	var calls []struct {
		BindAddr string
		Router   http.Handler
	}
	mock.lockGetHTTPServer.RLock()
	calls = mock.calls.GetHTTPServer
	mock.lockGetHTTPServer.RUnlock()
	return calls
}

// GetHealthCheck calls GetHealthCheckFunc.
func (mock *InitialiserMock) GetHealthCheck(cfg *config.Config, time string, commit string, version string) (service.HealthChecker, error) {
	if mock.GetHealthCheckFunc == nil {
		panic("InitialiserMock.GetHealthCheckFunc: method is nil but Initialiser.GetHealthCheck was just called")
	}
	callInfo := struct {
		Cfg     *config.Config
		Time    string
		Commit  string
		Version string
	}{
		Cfg:     cfg,
		Time:    time,
		Commit:  commit,
		Version: version,
	}
	mock.lockGetHealthCheck.Lock()
	mock.calls.GetHealthCheck = append(mock.calls.GetHealthCheck, callInfo)
	mock.lockGetHealthCheck.Unlock()
	return mock.GetHealthCheckFunc(cfg, time, commit, version)
}

// GetHealthCheckCalls gets all the calls that were made to GetHealthCheck.
// Check the length with:
//     len(mockedInitialiser.GetHealthCheckCalls())
func (mock *InitialiserMock) GetHealthCheckCalls() []struct {
	Cfg     *config.Config
	Time    string
	Commit  string
	Version string
} {
	var calls []struct {
		Cfg     *config.Config
		Time    string
		Commit  string
		Version string
	}
	mock.lockGetHealthCheck.RLock()
	calls = mock.calls.GetHealthCheck
	mock.lockGetHealthCheck.RUnlock()
	return calls
}

// GetResponder calls GetResponderFunc.
func (mock *InitialiserMock) GetResponder() service.Responder {
	if mock.GetResponderFunc == nil {
		panic("InitialiserMock.GetResponderFunc: method is nil but Initialiser.GetResponder was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetResponder.Lock()
	mock.calls.GetResponder = append(mock.calls.GetResponder, callInfo)
	mock.lockGetResponder.Unlock()
	return mock.GetResponderFunc()
}

// GetResponderCalls gets all the calls that were made to GetResponder.
// Check the length with:
//     len(mockedInitialiser.GetResponderCalls())
func (mock *InitialiserMock) GetResponderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetResponder.RLock()
	calls = mock.calls.GetResponder
	mock.lockGetResponder.RUnlock()
	return calls
}
